
== Consommation d'eau

== 2022

.Figure 1: Mètre cube par jour et par personne en moyenne depuis le début de l'année.
{sp}

++++
<div id="container_22" style="width: 800px; height: 400px;"></div>


<script>
// create data
var data = [
    ["26/02", 1.27],
    ["27/02", 1.27],

];

// create a chart
chart = anychart.cartesian();

// create a marker series and set the data
chart.marker(data);
chart.yAxis().title('mètre cube par jour et par personne en moyenne (2022)');
chart.xAxis().title('date de prélèvement');
chart.yScale().minimum(0);
var yAxis = chart.yAxis();
var lm_avg = chart.lineMarker();
lm_avg.axis(yAxis);
lm_avg.value(0.15);
lm_avg.stroke({color: 'green', thickness: 2, dash:'5 5', lineCap: 'round'});
var tm_avg = chart.textMarker();
tm_avg.axis(chart.yAxis());
tm_avg.value(0.2);
tm_avg.text("moyenne nationale: 0.15 m3 par jour et par personne");
tm_avg.offsetX(0);
tm_avg.fontColor('green');



// set the container id
chart.container("container_22");

// initiate drawing the chart
chart.draw();
</script>
++++

{sp} +
{sp} +

Actuellement, la consommation nationale française moyenne d’eau s’élève à
https://gaz-tarif-reglemente.fr/maitriser-sa-consommation/economies-energie/consommation-eau.html[150]
litres d’eau potable par jour et par personne, soit *0,15 m^3^*.
Pour comparer la consommation au Puid avec la consommation nationale (ligne verte en pointillé),
il faut choisir une valeur pour la population moyenne au Puid.
Actuellement, la valeur *100* est choisie, mais ce choix reste à délibérer.

++++
<iframe width='800' height='600' scrolling='no' style="background: #F1F5F4;border: none;border-radius: 2px;box-shadow: 0 2px 10px 0 rgba(70, 76, 79, .2);"  src="https://charts.mongodb.com/charts-m001-kqjgh/embed/dashboards?id=61dcd1f9-ae73-45c7-89bb-5b0b799aada2&theme=light&autoRefresh=true&maxDataAge=1&showTitleAndDesc=true&scalingWidth=fixed&scalingHeight=fixed"></iframe>
++++

=== 2021

.Figure 1: Mètre cube par jour et par personne en moyenne depuis le début de l'année (denière mise à jour 27.2.2022)
{sp}

++++
<div id="container_21" style="width: 800px; height: 400px;"></div>


<script>
// create data
var data = [
    ["16/02", 1.24],
    ["18/02", 1.21],
    ["21/02", 1.17],
    ["23/02", 1.15],
    ["01/03", 1.09],
    ["13/03", 1.00],
    ["28/03", 0.92],
    ["04/04", 0.89],
    ["10/04", 0.87],
    ["22/04", 0.83],
    ["25/04", 0.83],
    ["08/05", 0.79],
    ["16/05", 0.78],
    ["24/05", 0.76],
    ["02/06", 0.74],
    ["05/07", 0.71],
    ["15/07", 0.70],
    ["27/07", 0.70],
    ["03/08", 0.69],
    ["15/08", 0.68],
    ["28/08", 0.68],
    ["28/09", 0.67],
    ["28/09", 0.66],
    ["17/10", 0.65],
    ["26/11", 0.63],
    ["31/12", 0.71],
];

// create a chart
chart = anychart.cartesian();

// create a marker series and set the data
chart.marker(data);
chart.yAxis().title('mètre cube par jour et par personne en moyenne (2021)');
chart.xAxis().title('date de prélèvement');
chart.yScale().minimum(0);
var yAxis = chart.yAxis();
var lm_avg = chart.lineMarker();
lm_avg.axis(yAxis);
lm_avg.value(0.15);
lm_avg.stroke({color: 'green', thickness: 2, dash:'5 5', lineCap: 'round'});
var tm_avg = chart.textMarker();
tm_avg.axis(chart.yAxis());
tm_avg.value(0.2);
tm_avg.text("moyenne nationale: 0.15 m3 par jour et par personne");
tm_avg.offsetX(0);
tm_avg.fontColor('green');



// set the container id
chart.container("container_21");

// initiate drawing the chart
chart.draw();
</script>
++++

{sp} +
{sp} +


[caption="Tableau 1: "]

.Relevé du compteur par date (denière mise à jour 31.12.2021)
[cols="2,2,1,2,2,1"]
|===
|Date | Compteur | m^3^ |Date | Compteur | m^3^

|16/02 | 29251 | 1.24 |18/02 | 29349 | 1.21
|21/02 | 29512 | 1.17 |23/03 | 29640 | 1.15
|01/03 | 29960 | 1.09 |13/03 | 30559 | 1.00
|28/03 | 31348 | 0.92 |04/04 | 31723 | 0.89
|10/04 | 32072 | 0.87 |22/04 | 32725 | 0.83
|25/04 | 32898 | 0.83 |08/05 | 33528 | 0.79
|16/05 | 33964 | 0.78 |24/05 | 34364 | 0.76
|02/06 | 34760 | 0.74 |05/07 | 36641 | 0.71
|15/07 | 37133 | 0.70 |27/07 | 37848 | 0.70
|03/08 | 38166 | 0.69 |15/08 | 38903 | 0.68
|28/08 | 39636 | 0.68 |20/09 | 40878 | 0.67
|28/09 | 41265 | 0.66 |17/10 | 42295 | 0.65
|26/11 | 44285 | 0.63 | 31/12 | 49237 | 0.71

|===


*m^3^*: Mètre cube par jour et par personne en moyenne depuis le début de l'année. +

Relevé du compteur à la fin de l'année précédente (31/12/2020): *23295*
